apiVersion: v1
kind: ConfigMap
metadata:
  name: splitting1-configmap
data:
  layer_start: "0"
  layer_end: "10"
  nextaddr: "splitting2-service"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: splitting2-configmap
data:
  layer_start: "10"
  layer_end: "21"
  nextaddr: "None"
