apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitting1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitting1
  template:
    metadata:
      labels:
        app: splitting1
    spec:
      containers:
      - name: splitting1
        image: ownfos/splitting
        env:
          - name: LAYER_START
            valueFrom:
              configMapKeyRef:
                name: splitting1-config
                key: layer_start
          - name: LAYER_END
            valueFrom:
              configMapKeyRef:
                name: splitting1-config
                key: layer_end
          - name: NEXTADDR
            valueFrom:
              configMapKeyRef:
                name: splitting1-config
                key: nextaddr
        ports:
        - containerPort: 5000
        readinessProbe: null
        livenessProbe: null
        startupProbe: null
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
          requests:
            memory: "640Mi"
            cpu: "250m"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: splitting2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: splitting2
  template:
    metadata:
      labels:
        app: splitting2
    spec:
      containers:
      - name: splitting2
        image: ownfos/splitting
        env:
          - name: LAYER_START
            valueFrom:
              configMapKeyRef:
                name: splitting2-config
                key: layer_start
          - name: LAYER_END
            valueFrom:
              configMapKeyRef:
                name: splitting2-config
                key: layer_end
          - name: NEXTADDR
            valueFrom:
              configMapKeyRef:
                name: splitting2-config
                key: nextaddr
        ports:
        - containerPort: 5000
        readinessProbe: null
        livenessProbe: null
        startupProbe: null
        resources:
          limits:
            memory: "1280Mi"
            cpu: "500m"
          requests:
            memory: "640Mi"
            cpu: "250m"
