apiVersion: v1
kind: Service
metadata:
  name: splitting1-service
spec:
  selector:
    app: splitting1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: splitting2-service
spec:
  selector:
    app: splitting2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
